version: '3'

dotenv:
- .env
- .user

tasks:

    default:
        dir: packages
        cmds: 
        - nuv -wsk project deploy

    clean:
        dir: packages
        cmds: 
        - nuv -wsk project undeploy

    setup: |
      python3 -m venv venv
      source venv/bin/activate
      pip install ipython openai requests

    cli: |
        source venv/bin/activate
        ipython -i util/init.ipy
