version: '3'

dotenv:
- .env

vars:
    DRY: ""
    SKIP: ""

tasks:

    build:venv:
        requires: { vars: [A] }
        cmds:
        - cp "packages/{{.A}}/requirements.txt" "util/requirements.txt"
        - bash util/virtualenv.sh
        - mv util/virtualenv.zip "packages/{{.A}}.zip"
        - task: build:act
        sources:
        - "packages/{{.A}}/requirements.txt"
        generates:
        - "packages/{{.A}}.zip"

    build:act:
        aliases: [b]
        requires: { vars: [A] }
        cmds:
        - task: build:venv
        -   |
            FILE=$(basename "{{.A}}")
            cd packages/{{.A}}
            zip ../$FILE.zip  * -x requirements.txt
        sources:
        - packages/{{.A}}/*
        generates:
        - packages/{{.A}}.zip

    clean:
    - rm -v packages/*/*.zip

    setup: |
        for i in packages/*/*/requirements.txt
        do pip install -r $i
        done

    cli: |
        ipython -i util/init.ipy
    

    serve:
        aliases: [s]
        cmds:
        - http-server -a 127.0.0.1 web -c-1 --mimetypes util/mime.types  -P $MY_APIHOST

    auto:
        - python -m util.deploy -w
        



