version: '3'

dotenv:
- ../.user

tasks:

  setup:
    - |
      sudo npm install -g http-server

  default:
    cmds:
    - http-server -a 127.0.0.1 ../web -c-1  -P $APIMY

  virtualenv:
    cmds:
    - sudo docker run -u"$(id -u)" --entrypoint=/mnt/virtualenv.sh -v $PWD:/mnt ghcr.io/nuvolaris/action-python-v311:3.0.0-beta.2401111655

