version: '3'

dotenv:
- ../.user

vars:
  RUNTIME: "ghcr.io/nuvolaris/action-python-v311:3.0.0-beta.2401111655"

tasks:

  default:
    aliases: [serve]
    cmds:
    - http-server -a 127.0.0.1 ../web -c-1 --mimetypes mime.types  -P $APIMY

  setup:
    - |
      sudo npm install -g http-server
