version: '3'

dotenv:
- ../.env

vars:
  IMG: "ghcr.io/nuvolaris/mastrogpt-devcontainer"
  VER: "3.1.0-mastropt"
  TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest

tasks:

  build-and-push:
    -  docker login -u "$GITHUB_USER" -p "$GITHUB_TOKEN" ghcr.io 
    -  docker build .  --no-cache -t {{.IMG}}:{{.TAG}} --push

  image-tag:
    silent: true
    cmds:
    - git tag -d $(git tag) 
    - git tag -f {{.VER}}.$(date +%y%m%d%H%M)
    - env PAGER= git tag